$axure.loadCurrentPage({
  "url":"健康告知v1_1.html",
  "generationDate":new Date(1497839563172.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"39fa9a9c99a4461592dc56edb32adc58",
    "type":"Axure:Page",
    "name":"健康告知V1.1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8b7bea2e4b384241b0b4117fc0efe2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":414,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"044512e3ac1d463d92f201c0467c5725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":414,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康告知v1_1/u0.png"}},
{
          "id":"51db5b6cab6a4c5791cbc04048d20a09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":0,
              "y":58},
            "size":{
              "width":414,
              "height":92},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d2f7471de94450aa9451a2b41d631b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":0,
                  "y":58},
                "size":{
                  "width":414,
                  "height":92},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康告知v1_1/u2.png"}},
{
          "id":"9ce984e6d4844bafa628df9ce0aba2f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":18,
              "y":80},
            "size":{
              "width":379,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21ffb92ee24143088651d1015ec4ff98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":80},
                "size":{
                  "width":379,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61d93cb322a34c069e8efc5b56e69485",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":65,
              "y":109},
            "size":{
              "width":285,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd7000dd64f846899f1e5f55700594da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":65,
                  "y":109},
                "size":{
                  "width":285,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3619c040150642028b3abf4f8c8e8bcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":160},
            "size":{
              "width":393,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be4a14ca8ba94ed9959badfbfda14ffe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":160},
                "size":{
                  "width":393,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ea04ce1bfc74acbbb61b904d865e569",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":251},
            "size":{
              "width":391,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康告知v1_1/u10_line.png"}},
{
          "id":"28c33602aef74f969a46f8fa94511cd7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":358},
            "size":{
              "width":391,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康告知v1_1/u10_line.png"}},
{
          "id":"b165fdcf8d00418f98a9c4f0e62b84d3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":465},
            "size":{
              "width":391,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康告知v1_1/u10_line.png"}},
{
          "id":"72955b1a44d14c8fa741857ead51fddc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":572},
            "size":{
              "width":391,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康告知v1_1/u10_line.png"}},
{
          "id":"4924c5671a3843e980df589951e00992",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF26C6DA},
            "location":{
              "x":0,
              "y":710},
            "size":{
              "width":208,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecc5b3abbc68490bb700ee58a7ac6a33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF26C6DA},
                "location":{
                  "x":0,
                  "y":710},
                "size":{
                  "width":208,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康告知v1_1/u14.png"}},
{
          "id":"0c61f88e29614d01bf8953a1035f9176",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4D90E7},
            "location":{
              "x":206,
              "y":710},
            "size":{
              "width":208,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8d36bc5e4944523b92b7bd229eb45a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7},
                "location":{
                  "x":206,
                  "y":710},
                "size":{
                  "width":208,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康告知v1_1/u16.png"}},
{
          "id":"3b7e52dca9494b929a3411d585ca82e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":278,
              "y":719},
            "size":{
              "width":65,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2bb366704a04d6eb156ad477ba9b1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":719},
                "size":{
                  "width":65,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"017efb9c438c4935828932a0817cc9df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":72,
              "y":719},
            "size":{
              "width":65,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b854430f517e4a3283a9b85c757da640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":72,
                  "y":719},
                "size":{
                  "width":65,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b5fdd20fea044ec9f2455379994dbad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":271},
            "size":{
              "width":393,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"113ecbd59cdb4d2da43c516616e33844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":271},
                "size":{
                  "width":393,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f4bebdd69314e0d9c6b330e89849e93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":379},
            "size":{
              "width":393,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e218761be89247478b61b874e00fda65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":379},
                "size":{
                  "width":393,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfc3eb09486f4d90b4ab1b98cfb9ff59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":486},
            "size":{
              "width":393,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6a3408adad421e9cafff47f9b7c34b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":486},
                "size":{
                  "width":393,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"666546de404a45a0af00b1138164b3ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":600},
            "size":{
              "width":393,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b54eda3dcb3a48978a15644d163a1072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":600},
                "size":{
                  "width":393,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b200b9dcb8a74f789e011dcf3bcec4c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0",
            "location":{
              "x":206,
              "y":711},
            "size":{
              "width":208,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"339ad192db424e1686377c9377247eb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0",
                "location":{
                  "x":206,
                  "y":711},
                "size":{
                  "width":208,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 完善被保人信息V1.1",
                      "target":{
                        "targetType":"page",
                        "url":"完善被保人信息v1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8b7bea2e4b384241b0b4117fc0efe2a6":{
      "scriptId":"u0"},
    "044512e3ac1d463d92f201c0467c5725":{
      "scriptId":"u1"},
    "51db5b6cab6a4c5791cbc04048d20a09":{
      "scriptId":"u2"},
    "6d2f7471de94450aa9451a2b41d631b5":{
      "scriptId":"u3"},
    "9ce984e6d4844bafa628df9ce0aba2f9":{
      "scriptId":"u4"},
    "21ffb92ee24143088651d1015ec4ff98":{
      "scriptId":"u5"},
    "61d93cb322a34c069e8efc5b56e69485":{
      "scriptId":"u6"},
    "bd7000dd64f846899f1e5f55700594da":{
      "scriptId":"u7"},
    "3619c040150642028b3abf4f8c8e8bcb":{
      "scriptId":"u8"},
    "be4a14ca8ba94ed9959badfbfda14ffe":{
      "scriptId":"u9"},
    "5ea04ce1bfc74acbbb61b904d865e569":{
      "scriptId":"u10"},
    "28c33602aef74f969a46f8fa94511cd7":{
      "scriptId":"u11"},
    "b165fdcf8d00418f98a9c4f0e62b84d3":{
      "scriptId":"u12"},
    "72955b1a44d14c8fa741857ead51fddc":{
      "scriptId":"u13"},
    "4924c5671a3843e980df589951e00992":{
      "scriptId":"u14"},
    "ecc5b3abbc68490bb700ee58a7ac6a33":{
      "scriptId":"u15"},
    "0c61f88e29614d01bf8953a1035f9176":{
      "scriptId":"u16"},
    "b8d36bc5e4944523b92b7bd229eb45a8":{
      "scriptId":"u17"},
    "3b7e52dca9494b929a3411d585ca82e1":{
      "scriptId":"u18"},
    "b2bb366704a04d6eb156ad477ba9b1fe":{
      "scriptId":"u19"},
    "017efb9c438c4935828932a0817cc9df":{
      "scriptId":"u20"},
    "b854430f517e4a3283a9b85c757da640":{
      "scriptId":"u21"},
    "4b5fdd20fea044ec9f2455379994dbad":{
      "scriptId":"u22"},
    "113ecbd59cdb4d2da43c516616e33844":{
      "scriptId":"u23"},
    "3f4bebdd69314e0d9c6b330e89849e93":{
      "scriptId":"u24"},
    "e218761be89247478b61b874e00fda65":{
      "scriptId":"u25"},
    "dfc3eb09486f4d90b4ab1b98cfb9ff59":{
      "scriptId":"u26"},
    "8d6a3408adad421e9cafff47f9b7c34b":{
      "scriptId":"u27"},
    "666546de404a45a0af00b1138164b3ce":{
      "scriptId":"u28"},
    "b54eda3dcb3a48978a15644d163a1072":{
      "scriptId":"u29"},
    "b200b9dcb8a74f789e011dcf3bcec4c4":{
      "scriptId":"u30"},
    "339ad192db424e1686377c9377247eb3":{
      "scriptId":"u31"}}});