$axure.loadCurrentPage({
  "url":"订单查询v1_1.html",
  "generationDate":new Date(1497846645876.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9ac9f667ec7c45e49043a725e87a51d2",
    "type":"Axure:Page",
    "name":"订单查询V1.1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e63b4b167d4047f28ae63f04ca43ddf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":414,
              "height":600}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33201407acc24a7388928f49a18d060a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":414,
                  "height":600}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u0.png"}},
{
          "id":"7bdb328e6b494721b1279fcddcb25cc8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":68},
            "size":{
              "width":414,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/保险方案页面--家庭标准计划v1_2/u146_line.png"}},
{
          "id":"f1202e6864864d409283bdb22f7a6d2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":79},
            "size":{
              "width":22,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31ca0438e5e417398472f659fda8dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":79},
                "size":{
                  "width":22,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u3.png"}},
{
          "id":"fcd878a31ad14ffea9adc45656d15a7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Times New Roman Normal', 'Times New Roman'",
            "fontSize":"14px",
            "location":{
              "x":39,
              "y":80},
            "size":{
              "width":81,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33be84b8e07947e6ad3b873ee3de3196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Times New Roman Normal', 'Times New Roman'",
                "fontSize":"14px",
                "location":{
                  "x":39,
                  "y":80},
                "size":{
                  "width":81,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2103f9954b3643c7bdfc8af6f0f2aaa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"14px",
            "location":{
              "x":255,
              "y":80},
            "size":{
              "width":57,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aa10a4109164ddda78751abe0de4d1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"14px",
                "location":{
                  "x":255,
                  "y":80},
                "size":{
                  "width":57,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"504e16e6e2f8448bbe4afa6e8567451b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"14px",
            "location":{
              "x":340,
              "y":80},
            "size":{
              "width":57,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f3768b91f7942858c35537f67fa1a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"14px",
                "location":{
                  "x":340,
                  "y":80},
                "size":{
                  "width":57,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccebd7a0701e484eaec4835db735828c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":81},
            "size":{
              "width":28,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c864931606a14bd6943d739f8159c754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":81},
                "size":{
                  "width":28,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u11.png"}},
{
          "id":"b53a3199fa704921b178ee6f175d01f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":80},
            "size":{
              "width":22,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22c53ab227ed46c0bbcf8b0c8efd3fdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":80},
                "size":{
                  "width":22,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u13.png"}},
{
          "id":"bc5f591b7b8a43518b4e9deae319bf2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":18,
              "y":154},
            "size":{
              "width":377,
              "height":406},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd51cddd81f4cbbbc4773cc8da87202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":18,
                  "y":154},
                "size":{
                  "width":377,
                  "height":406},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u15.png"}},
{
          "id":"9f9af668cc5a463ca4a194110abd6e7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"18px",
            "location":{
              "x":62,
              "y":115},
            "size":{
              "width":289,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ee4672f3c1040598675884d599183d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"18px",
                "location":{
                  "x":62,
                  "y":115},
                "size":{
                  "width":289,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50d3b82ed4d847fb9b4dfcfe2baa75f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":170},
            "size":{
              "width":156,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18e947817c5405fba0f931d109e0562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":170},
                "size":{
                  "width":156,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f672e2c2ff144a1b61c6eb29e23baa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":30,
              "y":225},
            "size":{
              "width":168,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34a393f163ce40db8120f24f3bf0043a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":30,
                  "y":225},
                "size":{
                  "width":168,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2605a1fc944409a964a561389b594e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":198},
            "size":{
              "width":161,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae47509c74644255939528ad29886e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":198},
                "size":{
                  "width":161,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12c829b61e324a4699bf0a14a1e730ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":30,
              "y":394},
            "size":{
              "width":86,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0624e6eb19324843ba810672e192ccb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":30,
                  "y":394},
                "size":{
                  "width":86,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04aafd04b79f431fb288b0ea02998910",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":420},
            "size":{
              "width":118,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"168c6f74ae2b48ae9d73c44f4985d337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":420},
                "size":{
                  "width":118,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad12209db82b44879bd3e21c15db9c48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":30,
              "y":448},
            "size":{
              "width":105,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f528937cec404ab03cdebac286cc0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":30,
                  "y":448},
                "size":{
                  "width":105,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c8f8cfd792044ebbe89bedef66fd1ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "location":{
              "x":30,
              "y":476},
            "size":{
              "width":92,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9aed4a8f37f4af88ec31b90ed329b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "location":{
                  "x":30,
                  "y":476},
                "size":{
                  "width":92,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e61785761624c68a210a1e0cad56829",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D90E7,
              "opacity":1},
            "location":{
              "x":103,
              "y":510},
            "size":{
              "width":62,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D90E7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c3735ef27b04a5db2815f2065f21186",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7,
                  "opacity":1},
                "location":{
                  "x":103,
                  "y":510},
                "size":{
                  "width":62,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u33.png"}},
{
          "id":"a71d0398373944e6846ef6ba2b006b54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":253},
            "size":{
              "width":142,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14b8edb25d34ee487586986abdf5504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":253},
                "size":{
                  "width":142,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0284d145adc4a87af121642acdb8fb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":281},
            "size":{
              "width":142,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af4cb3f2ecd4fdfbd94e295e1d1efeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":281},
                "size":{
                  "width":142,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"938530d7131e4967b993d10866efc477",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":309},
            "size":{
              "width":161,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f529b12c88423382449956279b72c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":309},
                "size":{
                  "width":161,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86539d56998b414292d32578b19851bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":337},
            "size":{
              "width":264,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82bc5a8985a54d5ab80cf21be0fe1e41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":337},
                "size":{
                  "width":264,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c47aea06742445edb5a981bfbf5956b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":365},
            "size":{
              "width":104,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac1be08bde8d43e895734dc362f395ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":365},
                "size":{
                  "width":104,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cc6cc71b8e649c48897f916bc7f545b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D90E7,
              "opacity":1},
            "location":{
              "x":30,
              "y":510},
            "size":{
              "width":62,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D90E7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d60b81acdaf14160b7f4544107a2667e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":510},
                "size":{
                  "width":62,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u33.png"}},
{
          "id":"7a9dc41fb89341a880fd735c26bbe458",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D90E7,
              "opacity":1},
            "location":{
              "x":175,
              "y":510},
            "size":{
              "width":62,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D90E7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41cb12d73c1e450a9539aa452a9328a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7,
                  "opacity":1},
                "location":{
                  "x":175,
                  "y":510},
                "size":{
                  "width":62,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u33.png"}},
{
          "id":"b13bf295e7114bcf989044ab63ef573b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D90E7,
              "opacity":1},
            "location":{
              "x":320,
              "y":510},
            "size":{
              "width":62,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D90E7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e58ea116fed84e698dac2418647fdc65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":510},
                "size":{
                  "width":62,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u33.png"}},
{
          "id":"6360f8ccc6e544d1861562ea0150ad1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4D90E7,
              "opacity":1},
            "location":{
              "x":248,
              "y":510},
            "size":{
              "width":62,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4D90E7},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5731c82e4138408aadd1c69590f632a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7,
                  "opacity":1},
                "location":{
                  "x":248,
                  "y":510},
                "size":{
                  "width":62,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4D90E7},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单查询v1_1/u33.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e63b4b167d4047f28ae63f04ca43ddf1":{
      "scriptId":"u0"},
    "33201407acc24a7388928f49a18d060a":{
      "scriptId":"u1"},
    "7bdb328e6b494721b1279fcddcb25cc8":{
      "scriptId":"u2"},
    "f1202e6864864d409283bdb22f7a6d2f":{
      "scriptId":"u3"},
    "c31ca0438e5e417398472f659fda8dd8":{
      "scriptId":"u4"},
    "fcd878a31ad14ffea9adc45656d15a7b":{
      "scriptId":"u5"},
    "33be84b8e07947e6ad3b873ee3de3196":{
      "scriptId":"u6"},
    "2103f9954b3643c7bdfc8af6f0f2aaa7":{
      "scriptId":"u7"},
    "4aa10a4109164ddda78751abe0de4d1c":{
      "scriptId":"u8"},
    "504e16e6e2f8448bbe4afa6e8567451b":{
      "scriptId":"u9"},
    "3f3768b91f7942858c35537f67fa1a03":{
      "scriptId":"u10"},
    "ccebd7a0701e484eaec4835db735828c":{
      "scriptId":"u11"},
    "c864931606a14bd6943d739f8159c754":{
      "scriptId":"u12"},
    "b53a3199fa704921b178ee6f175d01f8":{
      "scriptId":"u13"},
    "22c53ab227ed46c0bbcf8b0c8efd3fdb":{
      "scriptId":"u14"},
    "bc5f591b7b8a43518b4e9deae319bf2b":{
      "scriptId":"u15"},
    "0fd51cddd81f4cbbbc4773cc8da87202":{
      "scriptId":"u16"},
    "9f9af668cc5a463ca4a194110abd6e7a":{
      "scriptId":"u17"},
    "2ee4672f3c1040598675884d599183d6":{
      "scriptId":"u18"},
    "50d3b82ed4d847fb9b4dfcfe2baa75f1":{
      "scriptId":"u19"},
    "a18e947817c5405fba0f931d109e0562":{
      "scriptId":"u20"},
    "7f672e2c2ff144a1b61c6eb29e23baa6":{
      "scriptId":"u21"},
    "34a393f163ce40db8120f24f3bf0043a":{
      "scriptId":"u22"},
    "c2605a1fc944409a964a561389b594e0":{
      "scriptId":"u23"},
    "ae47509c74644255939528ad29886e5c":{
      "scriptId":"u24"},
    "12c829b61e324a4699bf0a14a1e730ff":{
      "scriptId":"u25"},
    "0624e6eb19324843ba810672e192ccb2":{
      "scriptId":"u26"},
    "04aafd04b79f431fb288b0ea02998910":{
      "scriptId":"u27"},
    "168c6f74ae2b48ae9d73c44f4985d337":{
      "scriptId":"u28"},
    "ad12209db82b44879bd3e21c15db9c48":{
      "scriptId":"u29"},
    "b6f528937cec404ab03cdebac286cc0b":{
      "scriptId":"u30"},
    "9c8f8cfd792044ebbe89bedef66fd1ba":{
      "scriptId":"u31"},
    "e9aed4a8f37f4af88ec31b90ed329b7a":{
      "scriptId":"u32"},
    "7e61785761624c68a210a1e0cad56829":{
      "scriptId":"u33"},
    "9c3735ef27b04a5db2815f2065f21186":{
      "scriptId":"u34"},
    "a71d0398373944e6846ef6ba2b006b54":{
      "scriptId":"u35"},
    "f14b8edb25d34ee487586986abdf5504":{
      "scriptId":"u36"},
    "d0284d145adc4a87af121642acdb8fb9":{
      "scriptId":"u37"},
    "3af4cb3f2ecd4fdfbd94e295e1d1efeb":{
      "scriptId":"u38"},
    "938530d7131e4967b993d10866efc477":{
      "scriptId":"u39"},
    "e7f529b12c88423382449956279b72c8":{
      "scriptId":"u40"},
    "86539d56998b414292d32578b19851bb":{
      "scriptId":"u41"},
    "82bc5a8985a54d5ab80cf21be0fe1e41":{
      "scriptId":"u42"},
    "c47aea06742445edb5a981bfbf5956b0":{
      "scriptId":"u43"},
    "ac1be08bde8d43e895734dc362f395ee":{
      "scriptId":"u44"},
    "9cc6cc71b8e649c48897f916bc7f545b":{
      "scriptId":"u45"},
    "d60b81acdaf14160b7f4544107a2667e":{
      "scriptId":"u46"},
    "7a9dc41fb89341a880fd735c26bbe458":{
      "scriptId":"u47"},
    "41cb12d73c1e450a9539aa452a9328a7":{
      "scriptId":"u48"},
    "b13bf295e7114bcf989044ab63ef573b":{
      "scriptId":"u49"},
    "e58ea116fed84e698dac2418647fdc65":{
      "scriptId":"u50"},
    "6360f8ccc6e544d1861562ea0150ad1f":{
      "scriptId":"u51"},
    "5731c82e4138408aadd1c69590f632a4":{
      "scriptId":"u52"}}});